---
- name: Upgrade Windows OS using win_updates
  hosts: windows1  # Adjust to your target group (e.g., windows1)
  gather_facts: no

  tasks:
    - name: Install Windows feature updates (for OS upgrade)
      ansible.windows.win_updates:
        category_names: ['*'] # Complete upgrade
          #- FeaturePacks  # Targets major OS upgrades like Windows 11
          #- Updates
        state: installed
        reboot: yes  # Automatically reboot if required
      register: update_result

    - name: Verify OS version after upgrade
      ansible.windows.win_shell: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      register: os_version
      changed_when: false

    - name: Show upgrade results
      debug:
        msg: |
          Updates Installed: {{ update_result.updates | length }}
          Rebooted: {{ update_result.rebooted }}
          New OS Version: {{ os_version.stdout }}

